version: '3'

services:
  db:
    image: mysql:5.7
    env_file:
      - .env
  web:
    image: the2792/rails-test-app:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
#    command: bash -c "rails db:create RAILS_ENV=production && rails db:migrate RAILS_ENV=production&& rails server -b 0.0.0.0 -e production"
