version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build: .
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3050:80"
    depends_on:
      - web

volumes:
  db-data: