version: '3'

services:
  db:
    image: mysql:5.7
    env_file:
      - db.env
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - web.env
    command: bash -c "rails db:create && rails db:migrate && rails server -b 0.0.0.0"
