name: Deploy to AWS Lightsail EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: the2792/rails-test-app:latest
#          build-args: |
#            RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}
#            RAILS_SECRET=${{ secrets.RAILS_SECRET }}

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd rails-deploy
            rm -rf .env
            rm -rf config/master.key
            echo "${{ secrets.RAILS_MASTER_KEY }}" >> config/master.key
            echo "SECRET_KEY_BASE=${{ secrets.RAILS_SECRET }}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "RAILS_ENV=production" >> .env
#            echo "DATABASE_URL=mysql2://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@db/${{ secrets.MYSQL_DATABASE }}" >> .env
            ls -al
            git pull
            sudo docker-compose build
            sudo docker-compose up -d
#            sudo docker pull the2792/rails-test-app:latest
#            sudo docker ps
#            sudo docker images
#            sudo docker run -d -p 3000:3000 --env-file db.env --env-file web.env the2792/rails-test-app:latest
