name: Deploy to AWS Lightsail EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create db.env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> db.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> db.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> db.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> db.env
      - name: Create web.env file
        run: |
          echo "RAILS_ENV=production" >> web.env
          echo "DATABASE_URL=mysql2://${{ secrets.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@db/${{ secrets.MYSQL_DATABASE }}" >> web.env
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: the2792/rails-test-app:latest
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
      - name: Pull Docker image and start container
        run: |
          sudo docker pull the2792/rails-test-app:latest
          sudo docker run -d -p 3000:3000 --env-file db.env --env-file web.env the2792/rails-test-app:latest
